GET http://localhost:3000/api/utilizadores

###

POST http://localhost:3000/api/utilizadores

Content-Type: application/json
{
    "username": "rodri",
    "primeiro_nome": "Rodrigo",
    "ultimo_nome": "Oliveira",
    "email": "rodri009@gmail.com",
    "num_telemovel": "+9929378",
    "password": "sourodrigo"
}

